name = "harborpoint"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# -----------------------------

# D1 Databases
# Run these commands (replace names if desired):
#   wrangler d1 create harborpoint-members
#   wrangler d1 create harborpoint-members-preview
# Then copy the returned UUIDs into database_id fields below.
# -----------------------------
[[d1_databases]]
binding = "DB"                      # The binding used in code (env.DB)
database_name = "harborpoint-members"
database_id = "c741a91c-fdd5-43a4-bdce-341e9473de7a"

[vars]
# Generate a new 64-byte secret (example: openssl rand -base64 48) and place it here
JWT_SECRET = "REPLACE_WITH_SECURE_RANDOM_SECRET"
ENVIRONMENT = "production"

# (Preview environment removed per project preference)